### ISSUE TITLE
Inconsistency between license and README

### ISSUE THREAD

**Issue by nomlasvrc** [YamanamiV/ToN-RoundCounter#1]
This software is licensed under the MIT License, which includes the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell the software without restriction, so the following line in README.md:

> 改造等はご遠慮ください。二次配布等も禁止です。

is inconsistent with the license.

**Comment by YamanamiV** [comment]
That's certainly true.
The relevant parts have been corrected.

**Comment by nomlasvrc** [comment]
Thank you for correcting!
