### ISSUE TITLE
Adding new round types for the new update

### ISSUE THREAD

**Issue by Raifa21** [YamanamiV/ToN-RoundCounter#3]
Is there any intentions for updates for the new update? 
There might be problems with adding new counters though - its already close to the OSC param limit

**Comment by YamanamiV** [comment]
I can't solve the parameter problem because one count from 0 to 100 uses 8 bytes no matter how hard I try...
I tried to reduce it to 96 bytes by eliminating the Moon count.

**Comment by Raifa21** [comment]
I know this isn't ideal, but would it be possible to create one which sends it in the chatbox in the meantime?

**Comment by Raifa21** [comment]
I've seen that it has been done, so I'm going to go ahead and close this.
thanks for the update
